### ISSUE TITLE
Если в базе не находит ip, скрипт падает с FatalError

### ISSUE THREAD

**Issue by VGrigoryev** [himiklab/yii2-ipgeobase-component#3]
Если в IpGeoBase::getLocation передать ip, которого нет в БД, скрипт падает с FatalError.
Как я понял это из-за того, что IpGeoBase::fromDB возвращает false, который потом скалывается с массивом.
```php
$ipDataArray = $this->fromDB($ip) + ['ip' => $ip];
```

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-ipgeobase-component/commit/54972f68d0c8c6007db619ff43d11705c472189a

Исправил.
